In [1]:
import numpy as np


In [4]:
d=np.random.rand(3,3)
print(d)
labels= [0,2,1]
pred  = np.argmax(d,axis=1)


[[0.02997654 0.62885762 0.52677173]
 [0.79746143 0.13038322 0.77241267]
 [0.27747727 0.36276392 0.61212846]]


array([1, 0, 2])

In [12]:
npeople=5
nfeatures=7
    
np.random.choice([0, 1], size=(nfeatures,npeople), p=[1./nfeatures]*nfeatures)

ValueError: 'a' and 'p' must have same size

In [10]:
{‘’: 0, ‘’: 1, ‘’: 2, 
 ‘’: 4, ‘’: 5, ‘’: 6, ‘’: 7, 
 ‘’: 9, ‘’: 10, ‘’: 11, 
 ‘’: 12, ‘’: 13, ‘’: 14, ‘’: 15, 
 ‘’: 16, ‘’: 17, ‘’: 18, 
 ‘’: 20, ‘’: 21, ‘’: 22, ‘’: 23, 
 ‘’: 24, ‘’: 25, ‘’: 26, ‘’: 27, ‘’: 28, 
 ‘’: 29, ‘’: 30, ‘’: 31}



{'POLITICS':['NEWS', 'MILLITARY', 'POLITICS'],

'CORPORATE':['MARKETING', 'PR', 'RECRUITER', 'ASSISTANT', 'EXECUTIVE', 'SALES', 'FINANCE'],

'TRADES':['RESTAURANT JOB', 'WAITRESS', 'BEAUTY', 'ACTRESS/MODEL', 'DANCER', 'REALTOR', 'EVENT PLANNER', 'FITNESS', 'NANNY'],

'TRADITIONAL':['TEACHER','DENTIST', 'LAWYER', 'MEDICAL', 'SCIENCE/TECHNOLOGY'],

'OTHER':['STUDENTT', 'STUDENT', 'WRITER', 'PASTOR', 'ART', 'NONE', 'JOKE', 'FLIGHT ATTENDANT'],
 }

[0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285]

In [ ]:
{‘’: 0, 
 ‘’: 1, 
 ‘’: 2, 
 ‘’: 3, 
 ‘’: 4, 
 ‘’: 5, 
 ‘’: 6, 
 ‘’: 7, 
 ‘’: 8, 
 ‘’: 9}

{
    'INTERNATIONAL':['Canada','International'],
    'NE':['Midwestt','East','Midwest','Mid atlantic'],
    'NW':['West','Northwest'],
    'SE':['South',],
    'SW':['Southwest']
}
